Repository rubygarage/boilerplate, pull requests merged in 2020-10, with the labels that each got.

#227 Add FFaker config to share the same seed with RSpec
  Gemfile
  Gemfile.lock
  spec/support/config/ffaker.rb
Labels: feature, reviewed

#228 Feature | Added monthly gems update by dependabot
  .github/dependabot.yml
Labels: feature, reviewed

#249 PEO-1282 | add predicates `in` and `not_in`
  README.md
  app/concepts/api/v1/lib/operation/perform_filtering.rb
  app/concepts/api/v1/lib/operation/perform_ordering.rb
  config/initializers/json_api/filtering.rb
  lib/types/json_api.rb
  spec/concepts/api/v1/lib/operation/perform_filtering_spec.rb
  spec/concepts/api/v1/lib/operation/perform_ordering_spec.rb
Labels: feature, need review

#250 PEO-1283 | Added custom ransack predicate
  config/initializers/ransack.rb
  spec/concepts/api/v1/lib/operation/perform_filtering_spec.rb
Labels: feature, need review

#251 PEO-1286 | unify database.yml
  .circleci/config.yml
  .gitignore
  config/credentials.yml.enc
  config/credentials/test.yml.enc
  config/database.yml
  config/database.yml.ci
  config/database.yml.example
Labels: feature, need review

#252 PEO-1286 | update config
  Gemfile
  Gemfile.lock
  app/controllers/api_controller.rb
  config/credentials/test.yml.enc
  config/environments/development.rb
  config/environments/production.rb
  config/environments/staging.rb
  config/environments/test.rb
  config/initializers/cors.rb
  config/initializers/jwt_sessions.rb
  config/initializers/sentry.rb
  config/initializers/sidekiq.rb
  config/routes.rb
  config/webpacker.yml
  spec/controllers/api_controller_spec.rb
Labels: feature, need review

#254 Feature | Added encrypted credentials
  .gitignore
  config/credentials/development.yml.enc
  config/credentials/production.yml.enc
  config/credentials/staging.yml.enc
  config/credentials/test.yml.enc
  config/database.yml
  config/environments/development.rb
  config/initializers/sidekiq.rb
  config/webpacker.yml
  docker-entrypoint.sh
Labels: bugfix, need review
