Repository rubygarage/boilerplate, pull requests merged in 2020-09, with the labels that each got.

#182 Added config of dependabot
  .github/dependabot.yml
Labels: needs review

#183 PEO-1152 | Replace fast_jsonapi with jsonapi-serializer
  Gemfile
  Gemfile.lock
  app/concepts/application_serializer.rb
  spec/concepts/application_serializer_spec.rb
  spec/lib/service/json_api/resource_serializer_spec.rb
Labels: needs review

#167 PEO-1176 | Refactor docker image
  Dockerfile
Labels: enhancement, needs review

#178 PEO-1151 Replace overcommit with lefthook
  .circleci/config.yml
  .fasterer.yml
  .overcommit.yml
  .reek.yml
  .rubocop.yml
  .simplecov
  Gemfile
  Gemfile.lock
  config/environments/production.rb
  config/initializers/constants/shared.rb
  config/rails_best_practices.yml
  lefthook.yml
  lib/macro/schema.rb
Labels: feature, reviewed

#164 PEO-1174 | Add config of shrine
  .rubocop.yml
  Gemfile
  Gemfile.lock
  README.md
  app/uploaders/application_uploader.rb
  config/environments/development.rb
  config/environments/production.rb
  config/environments/test.rb
  config/initializers/shrine.rb
  spec/uploaders/application_uploader_spec.rb
Labels: feature, reviewed

#193 Fix filtering by boolean
  lib/types/json_api.rb
  spec/lib/types/json_api_spec.rb
Labels: bugfix, need review

#194 PEO-1177 | add dip to develop
  Gemfile
  Gemfile.lock
  README.md
  dip.yml
Labels: feature, need review

#165 PEO-1175 | Added activeadmin
  .browserslistrc
  .circleci/config.yml
  .gitignore
  .rubocop.yml
  Gemfile
  Gemfile.lock
  app/admin/admin_users.rb
  app/admin/dashboard.rb
  app/assets/config/manifest.js
  app/controllers/application_controller.rb
  app/models/admin_user.rb
  app/webpacker/packs/active_admin.js
  app/webpacker/packs/active_admin/print.scss
  app/webpacker/stylesheets/active_admin.scss
  babel.config.js
  bin/webpack
  bin/webpack-dev-server
  config/application.rb
  config/environments/test.rb
  config/initializers/active_admin.rb
  config/initializers/devise.rb
  config/locales/devise.en.yml
  config/routes.rb
  config/webpack/development.js
  config/webpack/environment.js
  config/webpack/plugins/jquery.js
  config/webpack/production.js
  config/webpack/test.js
  config/webpacker.yml
  db/migrate/20200831072010_devise_create_admin_users.rb
  db/schema.rb
  package.json
  postcss.config.js
  public/favicon.ico
  spec/controllers/application_controller_spec.rb
  spec/factories/admin_users.rb
  spec/features/admin/admin_users/edit_spec.rb
  spec/features/admin/admin_users/index_spec.rb
  spec/features/admin/admin_users/show_spec.rb
  spec/features/admin/sign_in_spec.rb
  spec/features/admin/sign_out_spec.rb
  spec/rails_helper.rb
  spec/support/config/capybara.rb
  yarn.lock
Labels: feature, reviewed

#146 PEO-1147 Bump ruby to 2.7.1
  .circleci/config.yml
  .ruby-version
  Gemfile.lock
  lib/macro/model.rb
  spec/concepts/api/v1/lib/service/json_api_spec.rb
  spec/concepts/api/v1/users/lib/service/session_token_spec.rb
  spec/lib/macro/assign_spec.rb
  spec/lib/macro/decorate_spec.rb
  spec/lib/macro/inject_spec.rb
  spec/lib/macro/model_delete_spec.rb
  spec/lib/macro/model_destroy_spec.rb
  spec/lib/macro/model_spec.rb
Labels: feature, need review

#196 PEO-1179 | Added sentry
  Gemfile
  Gemfile.lock
  README.md
  app/workers/application_worker.rb
  app/workers/sentry_worker.rb
  config/initializers/sentry.rb
  config/sidekiq.yml
  spec/workers/application_worker_spec.rb
  spec/workers/sentry_worker_spec.rb
Labels: feature, need review

#195 PEO-1178 | Added i18n-tasks
  .circleci/config.yml
  Gemfile
  Gemfile.lock
  config/i18n-tasks.yml
  config/locales/devise.en.yml
  config/locales/en.errors.yml
  config/locales/en.user_mailer.yml
  lefthook.yml
  spec/concepts/api/v1/lib/operation/filtering_spec.rb
  spec/concepts/api/v1/lib/operation/pagination_spec.rb
  spec/concepts/api/v1/lib/operation/sorting_spec.rb
  spec/concepts/api/v1/users/registrations/create_spec.rb
  spec/concepts/api/v1/users/reset_passwords/create_spec.rb
  spec/concepts/api/v1/users/reset_passwords/update_spec.rb
  spec/concepts/api/v1/users/sessions/create_spec.rb
  spec/concepts/api/v1/users/verifications/show_spec.rb
  spec/support/matchers/be_defined_in_i18n.rb
  spec/support/shared_examples/operation/errors_localizations.rb
  spec/support/shared_examples/operation/has_email_token_decryption_errors.rb
  spec/support/shared_examples/operation/has_email_token_equality_errors.rb
  spec/support/shared_examples/operation/nested_inclusion_errors.rb
Labels: feature, need review
