Repository rubygarage/boilerplate, pull requests merged in 2020-11, with the labels that each got.

#256 bugfix | tunning config
  .circleci/config.yml
  .dockerignore
  .ruby-version
  Dockerfile
  Gemfile
  Gemfile.lock
  README.md
  app/concepts/api/v1/users/reset_passwords/operation/create.rb
  app/concepts/api/v1/users/sessions/operation/create.rb
  app/controllers/concerns/default_endpoint.rb
  config/credentials/credentials.yml
  config/credentials/production.yml.enc
  config/credentials/staging.yml.enc
  config/environments/production.rb
  config/environments/test.rb
  config/locales/en.errors.yml
  config/routes.rb
  lib/macro/model_destroy.rb
  lib/macro/model_remove.rb
  spec/concepts/api/v1/users/reset_passwords/create_spec.rb
  spec/concepts/api/v1/users/sessions/create_spec.rb
  spec/features/admin/check_root_path_spec.rb
  spec/lib/macro/model_delete_spec.rb
  spec/lib/macro/model_destroy_spec.rb
  spec/lib/macro/model_remove_spec.rb
  spec/requests/api/v1/users/sessions_spec.rb
  spec/support/config/capybara.rb
Labels: bugfix, need review

#268 ISSUE-261 | Add description for password
  README.md
Labels: feature

#275 ISSUE-271 | Downgrade json_matchers
  Gemfile
  Gemfile.lock
Labels: feature, reviewed

#270 ISSUE-262 | Add refresh payload
  app/concepts/api/v1/users/lib/service/session_token.rb
  spec/concepts/api/v1/users/lib/service/session_token_spec.rb
Labels: feature

#277 ISSUE-276 | RemoveEmailNotification worker
  app/concepts/api/v1/users/lib/worker/email_notification.rb
  app/concepts/api/v1/users/reset_passwords/operation/update.rb
  app/concepts/api/v1/users/verifications/operation/show.rb
  config/sidekiq.yml
  spec/concepts/api/v1/users/account/profiles/show_spec.rb
  spec/concepts/api/v1/users/lib/worker/email_notification_spec.rb
  spec/concepts/api/v1/users/reset_passwords/update_spec.rb
  spec/concepts/api/v1/users/verifications/show_spec.rb
Labels: feature

#267 ISSUE-264 | Replace bullet to n_plus_one
  Gemfile
  Gemfile.lock
  config/initializers/bullet.rb
  spec/requests/api/v1/users/account/profiles_spec.rb
  spec/requests/api/v1/users/registrations_spec.rb
  spec/requests/api/v1/users/reset_passwords_spec.rb
  spec/requests/api/v1/users/session/refreshes_spec.rb
  spec/requests/api/v1/users/sessions_spec.rb
  spec/requests/api/v1/users/verifications_spec.rb
  spec/support/config/n_plus_one_control.rb
Labels: feature, need review
